Repository DdingSroom/dding-sroom-backend, pull requests merged in 2025-08, with the labels that each got.

#17 [Feat] 실시간 혼잡도 api & 예약 유효성 추가
  src/main/java/com/example/ddingsroom/reservation/controller/ReservationController.java
  src/main/java/com/example/ddingsroom/reservation/repository/ReservationRepository.java
  src/main/java/com/example/ddingsroom/reservation/service/ReservationService.java
Labels: ✨기능, 🎯리팩토링

#18 [Feat] 유저 이름 변경 api & 인증코드 유효 시간 제한
  src/main/java/com/example/ddingsroom/user/controller/JoinController.java
  src/main/java/com/example/ddingsroom/user/dto/ChangeUsernameDTO.java
  src/main/java/com/example/ddingsroom/user/service/JoinService.java
Labels: ✨기능, 🎯리팩토링

#21 [Feat] 예약취소, 예약, 회원탈퇴 유효성 검증, 회원탈퇴 방식 변경
  src/main/java/com/example/ddingsroom/reservation/repository/ReservationRepository.java
  src/main/java/com/example/ddingsroom/reservation/service/ReservationService.java
  src/main/java/com/example/ddingsroom/user/controller/JoinController.java
  src/main/java/com/example/ddingsroom/user/dto/EmailVerificationDTO.java
  src/main/java/com/example/ddingsroom/user/service/JoinService.java
Labels: ✨기능, 🎯리팩토링

#22 [Chore] 서비스 준비 설정 -> 시큐리티 허용범위 삭제
  src/main/java/com/example/ddingsroom/config/SecurityConfig.java
Labels: 🛠️ 설정

#33 [Chore] 테스트 환경 url CorsConfiguration 추가
  src/main/java/com/example/ddingsroom/community_post_comment/controller/CommunityPostCommentController.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/BaseResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentRequestDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/entity/CommunityPostCommentEntity.java
  src/main/java/com/example/ddingsroom/community_post_comment/repository/CommunityPostCommentRepository.java
  src/main/java/com/example/ddingsroom/community_post_comment/service/CommunityPostCommentService.java
  src/main/java/com/example/ddingsroom/config/SecurityConfig.java
Labels: 🌏인프라, 🛠️ 설정

#34 [Release] url 허용 범위 수정 병합
  src/main/java/com/example/ddingsroom/community_post_comment/controller/CommunityPostCommentController.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/BaseResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentRequestDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/entity/CommunityPostCommentEntity.java
  src/main/java/com/example/ddingsroom/community_post_comment/repository/CommunityPostCommentRepository.java
  src/main/java/com/example/ddingsroom/community_post_comment/service/CommunityPostCommentService.java
  src/main/java/com/example/ddingsroom/config/SecurityConfig.java
Labels: ✅ 릴리즈

#35 [Refactoring] Entity ID 타입 통일 및 JPA 관계 매핑 개선
  src/main/java/com/example/ddingsroom/admin/controller/AdminReservationController.java
  src/main/java/com/example/ddingsroom/admin/controller/AdminRoomController.java
  src/main/java/com/example/ddingsroom/admin/controller/AdminUserController.java
  src/main/java/com/example/ddingsroom/admin/dto/AdminUserDTO.java
  src/main/java/com/example/ddingsroom/admin/service/AdminReservationService.java
  src/main/java/com/example/ddingsroom/admin/service/AdminRoomService.java
  src/main/java/com/example/ddingsroom/admin/service/AdminUserService.java
  src/main/java/com/example/ddingsroom/community_post/entity/CommunityPostEntity.java
  src/main/java/com/example/ddingsroom/community_post/repository/CommunityPostRepository.java
  src/main/java/com/example/ddingsroom/community_post/service/CommunityPostService.java
  src/main/java/com/example/ddingsroom/community_post_comment/controller/CommunityPostCommentController.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/BaseResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentRequestDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/entity/CommunityPostCommentEntity.java
  src/main/java/com/example/ddingsroom/community_post_comment/repository/CommunityPostCommentRepository.java
  src/main/java/com/example/ddingsroom/community_post_comment/service/CommunityPostCommentService.java
  src/main/java/com/example/ddingsroom/config/SecurityUtils.java
  src/main/java/com/example/ddingsroom/notification/controller/NotificationController.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationRequestDTO.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationResponseDTO.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationUpdateRequestDTO.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationViewCountRequestDTO.java
  src/main/java/com/example/ddingsroom/notification/entity/NotificationEntity.java
  src/main/java/com/example/ddingsroom/notification/repository/NotificationRepository.java
  src/main/java/com/example/ddingsroom/notification/service/NotificationService.java
  src/main/java/com/example/ddingsroom/reservation/controller/ReservationController.java
  src/main/java/com/example/ddingsroom/reservation/dto/ReservationCancelRequestDTO.java
  src/main/java/com/example/ddingsroom/reservation/dto/ReservationRequestDTO.java
  src/main/java/com/example/ddingsroom/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/example/ddingsroom/reservation/entity/ReservationEntity.java
  src/main/java/com/example/ddingsroom/reservation/entity/RoomEntity.java
  src/main/java/com/example/ddingsroom/reservation/repository/ReservationRepository.java
  src/main/java/com/example/ddingsroom/reservation/repository/RoomRepository.java
  src/main/java/com/example/ddingsroom/reservation/service/ReservationService.java
  src/main/java/com/example/ddingsroom/suggest_post/entity/SuggestPostEntity.java
  src/main/java/com/example/ddingsroom/suggest_post/repository/SuggestPostRepository.java
  src/main/java/com/example/ddingsroom/suggest_post/service/SuggestPostSevice.java
  src/main/java/com/example/ddingsroom/suggest_post_comment/entity/SuggestPostCommentEntity.java
  src/main/java/com/example/ddingsroom/suggest_post_comment/repository/SuggestPostCommentRepository.java
  src/main/java/com/example/ddingsroom/suggest_post_comment/service/SuggestPostCommentService.java
  src/main/java/com/example/ddingsroom/user/controller/JoinController.java
  src/main/java/com/example/ddingsroom/user/controller/MainController.java
  src/main/java/com/example/ddingsroom/user/controller/ReissueController.java
  src/main/java/com/example/ddingsroom/user/dto/ChangeUsernameDTO.java
  src/main/java/com/example/ddingsroom/user/dto/MyPageDTO.java
  src/main/java/com/example/ddingsroom/user/entity/UserEntity.java
  src/main/java/com/example/ddingsroom/user/jwt/JWTFilter.java
  src/main/java/com/example/ddingsroom/user/jwt/JWTUtil.java
  src/main/java/com/example/ddingsroom/user/jwt/LoginFilter.java
  src/main/java/com/example/ddingsroom/user/repository/UserRepository.java
  src/main/java/com/example/ddingsroom/user/service/JoinService.java
Labels: 🎯리팩토링

#36 [Release] 리팩토링 배포
  src/main/java/com/example/ddingsroom/admin/controller/AdminReservationController.java
  src/main/java/com/example/ddingsroom/admin/controller/AdminRoomController.java
  src/main/java/com/example/ddingsroom/admin/controller/AdminUserController.java
  src/main/java/com/example/ddingsroom/admin/dto/AdminUserDTO.java
  src/main/java/com/example/ddingsroom/admin/service/AdminReservationService.java
  src/main/java/com/example/ddingsroom/admin/service/AdminRoomService.java
  src/main/java/com/example/ddingsroom/admin/service/AdminUserService.java
  src/main/java/com/example/ddingsroom/community_post/entity/CommunityPostEntity.java
  src/main/java/com/example/ddingsroom/community_post/repository/CommunityPostRepository.java
  src/main/java/com/example/ddingsroom/community_post/service/CommunityPostService.java
  src/main/java/com/example/ddingsroom/community_post_comment/controller/CommunityPostCommentController.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/BaseResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentRequestDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/dto/CommunityPostCommentResponseDTO.java
  src/main/java/com/example/ddingsroom/community_post_comment/entity/CommunityPostCommentEntity.java
  src/main/java/com/example/ddingsroom/community_post_comment/repository/CommunityPostCommentRepository.java
  src/main/java/com/example/ddingsroom/community_post_comment/service/CommunityPostCommentService.java
  src/main/java/com/example/ddingsroom/config/SecurityUtils.java
  src/main/java/com/example/ddingsroom/notification/controller/NotificationController.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationRequestDTO.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationResponseDTO.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationUpdateRequestDTO.java
  src/main/java/com/example/ddingsroom/notification/dto/NotificationViewCountRequestDTO.java
  src/main/java/com/example/ddingsroom/notification/entity/NotificationEntity.java
  src/main/java/com/example/ddingsroom/notification/repository/NotificationRepository.java
  src/main/java/com/example/ddingsroom/notification/service/NotificationService.java
  src/main/java/com/example/ddingsroom/reservation/controller/ReservationController.java
  src/main/java/com/example/ddingsroom/reservation/dto/ReservationCancelRequestDTO.java
  src/main/java/com/example/ddingsroom/reservation/dto/ReservationRequestDTO.java
  src/main/java/com/example/ddingsroom/reservation/dto/ReservationResponseDTO.java
  src/main/java/com/example/ddingsroom/reservation/entity/ReservationEntity.java
  src/main/java/com/example/ddingsroom/reservation/entity/RoomEntity.java
  src/main/java/com/example/ddingsroom/reservation/repository/ReservationRepository.java
  src/main/java/com/example/ddingsroom/reservation/repository/RoomRepository.java
  src/main/java/com/example/ddingsroom/reservation/service/ReservationService.java
  src/main/java/com/example/ddingsroom/suggest_post/entity/SuggestPostEntity.java
  src/main/java/com/example/ddingsroom/suggest_post/repository/SuggestPostRepository.java
  src/main/java/com/example/ddingsroom/suggest_post/service/SuggestPostSevice.java
  src/main/java/com/example/ddingsroom/suggest_post_comment/entity/SuggestPostCommentEntity.java
  src/main/java/com/example/ddingsroom/suggest_post_comment/repository/SuggestPostCommentRepository.java
  src/main/java/com/example/ddingsroom/suggest_post_comment/service/SuggestPostCommentService.java
  src/main/java/com/example/ddingsroom/user/controller/JoinController.java
  src/main/java/com/example/ddingsroom/user/controller/MainController.java
  src/main/java/com/example/ddingsroom/user/controller/ReissueController.java
  src/main/java/com/example/ddingsroom/user/dto/ChangeUsernameDTO.java
  src/main/java/com/example/ddingsroom/user/dto/MyPageDTO.java
  src/main/java/com/example/ddingsroom/user/entity/UserEntity.java
  src/main/java/com/example/ddingsroom/user/jwt/JWTFilter.java
  src/main/java/com/example/ddingsroom/user/jwt/JWTUtil.java
  src/main/java/com/example/ddingsroom/user/jwt/LoginFilter.java
  src/main/java/com/example/ddingsroom/user/repository/UserRepository.java
  src/main/java/com/example/ddingsroom/user/service/JoinService.java
Labels: 🎯리팩토링

#37 [Refactoring] 건의함 내역 조회 오류 해결
  src/main/java/com/example/ddingsroom/admin/service/AdminUserService.java
  src/main/java/com/example/ddingsroom/suggest_post/service/SuggestPostSevice.java
  src/main/java/com/example/ddingsroom/user/service/JoinService.java
Labels: 🎯리팩토링

#38 [Release] 건의함 오류 해결 병합
  src/main/java/com/example/ddingsroom/admin/service/AdminUserService.java
  src/main/java/com/example/ddingsroom/suggest_post/service/SuggestPostSevice.java
  src/main/java/com/example/ddingsroom/user/service/JoinService.java
Labels: ✅ 릴리즈

#44 [Release] 카테고리('신고') 및 위치('기타') 선택지 추가
  src/main/java/com/example/ddingsroom/suggest_post/util/SuggestPostCategory.java
  src/main/java/com/example/ddingsroom/suggest_post/util/SuggestPostLocation.java
Labels: ✅ 릴리즈

#46 [Release] 카테고리명 변경 ('신고' -> '미예약사용자 신고')
  src/main/java/com/example/ddingsroom/suggest_post/util/SuggestPostCategory.java
Labels: ✅ 릴리즈

#48 [Release] 공지사항 컬럼 타입 변경 배포
  src/main/java/com/example/ddingsroom/notification/entity/NotificationEntity.java
Labels: ✅ 릴리즈

#49 [Refactorying] 위치 '기타' 값 제거
  src/main/java/com/example/ddingsroom/suggest_post/util/SuggestPostLocation.java
Labels: 🎯리팩토링
